-- Crea la tabella 'luoghi' se non esiste
create table public.luoghi (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  luogo text not null,
  colore text default '#3b82f6'::text
);

-- Abilita RLS (Row Level Security) - Opzionale ma consigliato
alter table public.luoghi enable row level security;

-- Crea una policy per permettere tutto a tutti (per semplicità in fase di sviluppo)
-- ATTENZIONE: In produzione dovresti restringere gli accessi
create policy "Enable all access for all users" on public.luoghi
for all using (true) with check (true);

-- Inserisci alcuni luoghi di esempio
insert into public.luoghi (luogo, colore) values
('Sede Centrale', '#ef4444'),
('Distaccamento Nord', '#3b82f6'),
('Ospedale Civile', '#10b981');
