-- Crea la tabella 'luoghi'
create table public.luoghi (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  luogo text not null,
  colore text
);

-- Abilita RLS (Row Level Security) opzionale, ma consigliato su Supabase
alter table public.luoghi enable row level security;

-- Crea una policy per permettere accesso pubblico (lettura/scrittura) 
-- NOTA: In produzione dovresti restringere le policy.
create policy "Public Access" on public.luoghi for all using (true) with check (true);
